### ISSUE TITLE
webView 에서 외부 앱 호출 시 "unsupported URL"

### ISSUE THREAD

**Issue by mediio-david** [bootpay/react-native-bootpay#6]
pg: nicepay
device: iOS
payMethod: card

![IMG_0837](https://user-images.githubusercontent.com/73806676/105564225-92722900-5d64-11eb-8347-808f79f2cfc7.PNG)

pg 사를 danal로 바꾸면 문제가 발생하지 않습니다.

**Comment by quanndh** [comment]
this need to be reopen
